name: docker-build-push

on:
  workflow_dispatch:
env:
  IMAGE_NAME: zzci/traefik

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build docker tag
        id: tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          Build="$IMAGE_NAME:$VERSION"

          Date=`date "+%Y%m%d"`
          Date="$IMAGE_NAME:$Date"

          echo "tag-date=$Date" >> $GITHUB_ENV
          echo "tag-build=$Build" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ env.tag-date }}
            ${{ env.tag-build }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
